name: esptouch_example
description: Demonstrates how to use the esptouch plugin.
publish_to: 'none'
version: 0.1.5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  firebase_core: ^0.5.0+1
  flutter_signin_button: ^1.0.0

  esptouch_flutter:
    path: ../

flutter:
  uses-material-design: true

  assets:
   - images/
